name: .NET Core CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET 6.0
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '6.0.x'

    - name: Restore dependencies
      run: dotnet restore ./BackendApi/BackendApi.sln

    - name: Build
      run: dotnet build ./BackendApi/BackendApi.sln --configuration Release --no-restore

    - name: Test
      run: dotnet test ./BackendApi/BackendApi.sln --configuration Release --no-build