name: dotnet format

on:
  push:
    paths:
      - "**.cs"
      - ".editorconfig"
  pull_request:
    paths:
      - "**.cs"
      - ".editorconfig"

jobs:
  check-format:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET 6.0
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '6.0.x'

      - name: Check formatting
        run: dotnet format ./BackendApi/BackendApi.sln --verify-no-changes --verbosity diagnostic