name: Build and Code Format Check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-format:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '6.0.x'

      - name: Restore dependencies
        run: dotnet restore ./BackendApi/BackendApi.sln

      - name: Check code formatting
        run: dotnet format ./BackendApi/BackendApi.sln --verify-no-changes --verbosity normal

      - name: Build project
        run: dotnet build ./BackendApi/BackendApi.sln --configuration Release --no-restore